server.port=9090
spring.application.name=jinbu

# Database config
spring.datasource.url=jdbc:mysql://localhost:3308/db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql

# Max image size
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# AWS congig
cloud.aws.credentials.access-key=ASIAZ6QMJ7KDUBIPFET3
cloud.aws.credentials.secret-key=MzzcPX+1iqBpWfHPuqZh7/i3Ev3IJhTzFWydfUMA
cloud.aws.region.static=us-east-1

aws.bucket.name=jinbu-s3-bucket
aws.bucket.name2=jinbu-s3-profilepictures


