server.port=9090
spring.application.name=jinbu

# Database config
spring.datasource.url=jdbc:mysql://localhost:3308/db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql

# Max image size
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# AWS congig
cloud.aws.credentials.access-key=ASIAZ6QMJ7KDXBQ5ECVG
cloud.aws.credentials.secret-key=FDh3eh2fOuFL2WZZ3k6qAmJkvYRe6TFW9kngAa7V
cloud.aws.region.static=us-east-1

aws.bucket.name=jinbu-s3-bucket


